# Generated by Django 6.0.7 on 2026-07-31 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_token_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the last password reset was requested, used to expire old links.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token used for password reset links. Regenerated each time a reset is requested.'),
        ),
    ]
