# Generated by Django 6.0.7 on 2026-08-01 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='wish_template_covers/')),
                ('estimated_budget_min', models.PositiveIntegerField(blank=True, help_text="Estimated minimum cost in the platform's base currency.", null=True)),
                ('estimated_budget_max', models.PositiveIntegerField(blank=True, help_text="Estimated maximum cost in the platform's base currency.", null=True)),
                ('estimated_duration', models.CharField(blank=True, help_text="Human-readable duration estimate, e.g. '2 weeks' or '3 months'.", max_length=100)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], max_length=15)),
                ('suggested_season', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Helpful search tags, e.g. ['mountains', 'nepal', 'trekking'].")),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished templates are hidden from users but kept for editing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this wish belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='wish_templates', to='categories.category')),
            ],
            options={
                'db_table': 'wish_templates_wishtemplate',
                'ordering': ['-created_at'],
            },
        ),
    ]
