# Generated by Django 6.0.7 on 2026-08-01 06:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text="Stable internal identifier, e.g. 'travel'. Never shown to users directly.", unique=True)),
                ('name', models.CharField(help_text="Display name shown to users, e.g. 'Travel'.", max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier for the frontend (e.g. an icon name like 'plane').", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order categories appear in, lower numbers first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from users but preserved for existing wishes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories_category',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
