# Generated by Django 6.0.7 on 2026-07-28 07:22

import django.db.models.deletion
import user_profiles.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short biography, max 500 characters.', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, help_text='Optional profile picture. Falls back to a default avatar in the frontend if not set.', null=True, upload_to=user_profiles.models.profile_picture_upload_path)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(default='en', help_text="ISO language code, e.g. 'en', 'hi'. Used for future multilingual support.", max_length=10)),
                ('budget_preference', models.CharField(blank=True, choices=[('low', 'Low budget'), ('medium', 'Medium budget'), ('high', 'High budget')], max_length=10)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this profile is visible to other users.')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Set to True once the user finishes (or skips) onboarding.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'profiles_userprofile',
            },
        ),
    ]
