# Generated by Django 6.0.7 on 2026-07-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience_scope_preference',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('national', 'National'), ('international', 'International')], max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group_preference',
            field=models.CharField(blank=True, choices=[('solo', 'Solo'), ('couple', 'Couple'), ('friends', 'Friends'), ('family', 'Family')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text="List of interest tags selected during onboarding, e.g. ['travel', 'fitness']."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wish_type_preference',
            field=models.JSONField(blank=True, default=list, help_text="List of preferred wish categories, e.g. ['travel', 'education']."),
        ),
    ]
