# Generated by Django 6.0.7 on 2026-08-02 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('wish_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='wish_covers/')),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('saved', 'Saved'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='idea', max_length=20)),
                ('priority', models.BooleanField(default=False, help_text='Whether the user has marked this wish as a priority.')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this wish is visible to other users.')),
                ('estimated_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_wishes', to='categories.category')),
                ('source_template', models.ForeignKey(blank=True, help_text='If this wish was added from a recommended template, this links back to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by_users', to='wish_templates.wishtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishes_userwish',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='wishes.userwish')),
            ],
            options={
                'db_table': 'wishes_wishstatushistory',
                'ordering': ['-changed_at'],
            },
        ),
    ]
