# Generated by Django 6.0.7 on 2026-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwish',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Wish', 'verbose_name_plural': 'User Wishes'},
        ),
        migrations.AlterModelOptions(
            name='wishstatushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Wish Status History', 'verbose_name_plural': 'Wish Status Histories'},
        ),
        migrations.AlterField(
            model_name='userwish',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userwish',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
